/*
OpenDota API

Testing HeroesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_HeroesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HeroesAPIService GetHeroes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.HeroesAPI.GetHeroes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeroesAPIService GetHeroesByHeroIdSelectDurations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var heroId int32

		resp, httpRes, err := apiClient.HeroesAPI.GetHeroesByHeroIdSelectDurations(context.Background(), heroId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeroesAPIService GetHeroesByHeroIdSelectItemPopularity", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var heroId int32

		resp, httpRes, err := apiClient.HeroesAPI.GetHeroesByHeroIdSelectItemPopularity(context.Background(), heroId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeroesAPIService GetHeroesByHeroIdSelectMatches", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var heroId int32

		resp, httpRes, err := apiClient.HeroesAPI.GetHeroesByHeroIdSelectMatches(context.Background(), heroId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeroesAPIService GetHeroesByHeroIdSelectMatchups", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var heroId int32

		resp, httpRes, err := apiClient.HeroesAPI.GetHeroesByHeroIdSelectMatchups(context.Background(), heroId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeroesAPIService GetHeroesByHeroIdSelectPlayers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var heroId int32

		resp, httpRes, err := apiClient.HeroesAPI.GetHeroesByHeroIdSelectPlayers(context.Background(), heroId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
