/*
OpenDota API

Testing TeamsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_TeamsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TeamsAPIService GetTeams", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TeamsAPI.GetTeams(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TeamsAPIService GetTeamsByTeamId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var teamId int32

		resp, httpRes, err := apiClient.TeamsAPI.GetTeamsByTeamId(context.Background(), teamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TeamsAPIService GetTeamsByTeamIdSelectHeroes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var teamId int32

		resp, httpRes, err := apiClient.TeamsAPI.GetTeamsByTeamIdSelectHeroes(context.Background(), teamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TeamsAPIService GetTeamsByTeamIdSelectMatches", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var teamId int32

		resp, httpRes, err := apiClient.TeamsAPI.GetTeamsByTeamIdSelectMatches(context.Background(), teamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TeamsAPIService GetTeamsByTeamIdSelectPlayers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var teamId int32

		resp, httpRes, err := apiClient.TeamsAPI.GetTeamsByTeamIdSelectPlayers(context.Background(), teamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
