/*
OpenDota API

# Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     

API version: 25.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PlayersResponseProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlayersResponseProfile{}

// PlayersResponseProfile profile
type PlayersResponseProfile struct {
	// The player account ID
	AccountId *int32 `json:"account_id,omitempty"`
	// Player's Steam name
	Personaname NullableString `json:"personaname,omitempty"`
	// name
	Name NullableString `json:"name,omitempty"`
	// Boolean indicating status of current Dota Plus subscription
	Plus *bool `json:"plus,omitempty"`
	// cheese
	Cheese NullableInt32 `json:"cheese,omitempty"`
	// steamid
	Steamid NullableString `json:"steamid,omitempty"`
	// avatar
	Avatar NullableString `json:"avatar,omitempty"`
	// avatarmedium
	Avatarmedium NullableString `json:"avatarmedium,omitempty"`
	// avatarfull
	Avatarfull NullableString `json:"avatarfull,omitempty"`
	// profileurl
	Profileurl NullableString `json:"profileurl,omitempty"`
	// last_login
	LastLogin NullableString `json:"last_login,omitempty"`
	// loccountrycode
	Loccountrycode NullableString `json:"loccountrycode,omitempty"`
	// Boolean indicating if the user contributed to the development of OpenDota
	IsContributor *bool `json:"is_contributor,omitempty"`
	// Boolean indicating if the user subscribed to OpenDota
	IsSubscriber *bool `json:"is_subscriber,omitempty"`
}

// NewPlayersResponseProfile instantiates a new PlayersResponseProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayersResponseProfile() *PlayersResponseProfile {
	this := PlayersResponseProfile{}
	var isContributor bool = false
	this.IsContributor = &isContributor
	var isSubscriber bool = false
	this.IsSubscriber = &isSubscriber
	return &this
}

// NewPlayersResponseProfileWithDefaults instantiates a new PlayersResponseProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayersResponseProfileWithDefaults() *PlayersResponseProfile {
	this := PlayersResponseProfile{}
	var isContributor bool = false
	this.IsContributor = &isContributor
	var isSubscriber bool = false
	this.IsSubscriber = &isSubscriber
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *PlayersResponseProfile) GetAccountId() int32 {
	if o == nil || IsNil(o.AccountId) {
		var ret int32
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayersResponseProfile) GetAccountIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given int32 and assigns it to the AccountId field.
func (o *PlayersResponseProfile) SetAccountId(v int32) {
	o.AccountId = &v
}

// GetPersonaname returns the Personaname field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayersResponseProfile) GetPersonaname() string {
	if o == nil || IsNil(o.Personaname.Get()) {
		var ret string
		return ret
	}
	return *o.Personaname.Get()
}

// GetPersonanameOk returns a tuple with the Personaname field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayersResponseProfile) GetPersonanameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Personaname.Get(), o.Personaname.IsSet()
}

// HasPersonaname returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasPersonaname() bool {
	if o != nil && o.Personaname.IsSet() {
		return true
	}

	return false
}

// SetPersonaname gets a reference to the given NullableString and assigns it to the Personaname field.
func (o *PlayersResponseProfile) SetPersonaname(v string) {
	o.Personaname.Set(&v)
}
// SetPersonanameNil sets the value for Personaname to be an explicit nil
func (o *PlayersResponseProfile) SetPersonanameNil() {
	o.Personaname.Set(nil)
}

// UnsetPersonaname ensures that no value is present for Personaname, not even an explicit nil
func (o *PlayersResponseProfile) UnsetPersonaname() {
	o.Personaname.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayersResponseProfile) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayersResponseProfile) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *PlayersResponseProfile) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *PlayersResponseProfile) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *PlayersResponseProfile) UnsetName() {
	o.Name.Unset()
}

// GetPlus returns the Plus field value if set, zero value otherwise.
func (o *PlayersResponseProfile) GetPlus() bool {
	if o == nil || IsNil(o.Plus) {
		var ret bool
		return ret
	}
	return *o.Plus
}

// GetPlusOk returns a tuple with the Plus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayersResponseProfile) GetPlusOk() (*bool, bool) {
	if o == nil || IsNil(o.Plus) {
		return nil, false
	}
	return o.Plus, true
}

// HasPlus returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasPlus() bool {
	if o != nil && !IsNil(o.Plus) {
		return true
	}

	return false
}

// SetPlus gets a reference to the given bool and assigns it to the Plus field.
func (o *PlayersResponseProfile) SetPlus(v bool) {
	o.Plus = &v
}

// GetCheese returns the Cheese field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayersResponseProfile) GetCheese() int32 {
	if o == nil || IsNil(o.Cheese.Get()) {
		var ret int32
		return ret
	}
	return *o.Cheese.Get()
}

// GetCheeseOk returns a tuple with the Cheese field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayersResponseProfile) GetCheeseOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cheese.Get(), o.Cheese.IsSet()
}

// HasCheese returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasCheese() bool {
	if o != nil && o.Cheese.IsSet() {
		return true
	}

	return false
}

// SetCheese gets a reference to the given NullableInt32 and assigns it to the Cheese field.
func (o *PlayersResponseProfile) SetCheese(v int32) {
	o.Cheese.Set(&v)
}
// SetCheeseNil sets the value for Cheese to be an explicit nil
func (o *PlayersResponseProfile) SetCheeseNil() {
	o.Cheese.Set(nil)
}

// UnsetCheese ensures that no value is present for Cheese, not even an explicit nil
func (o *PlayersResponseProfile) UnsetCheese() {
	o.Cheese.Unset()
}

// GetSteamid returns the Steamid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayersResponseProfile) GetSteamid() string {
	if o == nil || IsNil(o.Steamid.Get()) {
		var ret string
		return ret
	}
	return *o.Steamid.Get()
}

// GetSteamidOk returns a tuple with the Steamid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayersResponseProfile) GetSteamidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Steamid.Get(), o.Steamid.IsSet()
}

// HasSteamid returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasSteamid() bool {
	if o != nil && o.Steamid.IsSet() {
		return true
	}

	return false
}

// SetSteamid gets a reference to the given NullableString and assigns it to the Steamid field.
func (o *PlayersResponseProfile) SetSteamid(v string) {
	o.Steamid.Set(&v)
}
// SetSteamidNil sets the value for Steamid to be an explicit nil
func (o *PlayersResponseProfile) SetSteamidNil() {
	o.Steamid.Set(nil)
}

// UnsetSteamid ensures that no value is present for Steamid, not even an explicit nil
func (o *PlayersResponseProfile) UnsetSteamid() {
	o.Steamid.Unset()
}

// GetAvatar returns the Avatar field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayersResponseProfile) GetAvatar() string {
	if o == nil || IsNil(o.Avatar.Get()) {
		var ret string
		return ret
	}
	return *o.Avatar.Get()
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayersResponseProfile) GetAvatarOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Avatar.Get(), o.Avatar.IsSet()
}

// HasAvatar returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasAvatar() bool {
	if o != nil && o.Avatar.IsSet() {
		return true
	}

	return false
}

// SetAvatar gets a reference to the given NullableString and assigns it to the Avatar field.
func (o *PlayersResponseProfile) SetAvatar(v string) {
	o.Avatar.Set(&v)
}
// SetAvatarNil sets the value for Avatar to be an explicit nil
func (o *PlayersResponseProfile) SetAvatarNil() {
	o.Avatar.Set(nil)
}

// UnsetAvatar ensures that no value is present for Avatar, not even an explicit nil
func (o *PlayersResponseProfile) UnsetAvatar() {
	o.Avatar.Unset()
}

// GetAvatarmedium returns the Avatarmedium field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayersResponseProfile) GetAvatarmedium() string {
	if o == nil || IsNil(o.Avatarmedium.Get()) {
		var ret string
		return ret
	}
	return *o.Avatarmedium.Get()
}

// GetAvatarmediumOk returns a tuple with the Avatarmedium field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayersResponseProfile) GetAvatarmediumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Avatarmedium.Get(), o.Avatarmedium.IsSet()
}

// HasAvatarmedium returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasAvatarmedium() bool {
	if o != nil && o.Avatarmedium.IsSet() {
		return true
	}

	return false
}

// SetAvatarmedium gets a reference to the given NullableString and assigns it to the Avatarmedium field.
func (o *PlayersResponseProfile) SetAvatarmedium(v string) {
	o.Avatarmedium.Set(&v)
}
// SetAvatarmediumNil sets the value for Avatarmedium to be an explicit nil
func (o *PlayersResponseProfile) SetAvatarmediumNil() {
	o.Avatarmedium.Set(nil)
}

// UnsetAvatarmedium ensures that no value is present for Avatarmedium, not even an explicit nil
func (o *PlayersResponseProfile) UnsetAvatarmedium() {
	o.Avatarmedium.Unset()
}

// GetAvatarfull returns the Avatarfull field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayersResponseProfile) GetAvatarfull() string {
	if o == nil || IsNil(o.Avatarfull.Get()) {
		var ret string
		return ret
	}
	return *o.Avatarfull.Get()
}

// GetAvatarfullOk returns a tuple with the Avatarfull field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayersResponseProfile) GetAvatarfullOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Avatarfull.Get(), o.Avatarfull.IsSet()
}

// HasAvatarfull returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasAvatarfull() bool {
	if o != nil && o.Avatarfull.IsSet() {
		return true
	}

	return false
}

// SetAvatarfull gets a reference to the given NullableString and assigns it to the Avatarfull field.
func (o *PlayersResponseProfile) SetAvatarfull(v string) {
	o.Avatarfull.Set(&v)
}
// SetAvatarfullNil sets the value for Avatarfull to be an explicit nil
func (o *PlayersResponseProfile) SetAvatarfullNil() {
	o.Avatarfull.Set(nil)
}

// UnsetAvatarfull ensures that no value is present for Avatarfull, not even an explicit nil
func (o *PlayersResponseProfile) UnsetAvatarfull() {
	o.Avatarfull.Unset()
}

// GetProfileurl returns the Profileurl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayersResponseProfile) GetProfileurl() string {
	if o == nil || IsNil(o.Profileurl.Get()) {
		var ret string
		return ret
	}
	return *o.Profileurl.Get()
}

// GetProfileurlOk returns a tuple with the Profileurl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayersResponseProfile) GetProfileurlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Profileurl.Get(), o.Profileurl.IsSet()
}

// HasProfileurl returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasProfileurl() bool {
	if o != nil && o.Profileurl.IsSet() {
		return true
	}

	return false
}

// SetProfileurl gets a reference to the given NullableString and assigns it to the Profileurl field.
func (o *PlayersResponseProfile) SetProfileurl(v string) {
	o.Profileurl.Set(&v)
}
// SetProfileurlNil sets the value for Profileurl to be an explicit nil
func (o *PlayersResponseProfile) SetProfileurlNil() {
	o.Profileurl.Set(nil)
}

// UnsetProfileurl ensures that no value is present for Profileurl, not even an explicit nil
func (o *PlayersResponseProfile) UnsetProfileurl() {
	o.Profileurl.Unset()
}

// GetLastLogin returns the LastLogin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayersResponseProfile) GetLastLogin() string {
	if o == nil || IsNil(o.LastLogin.Get()) {
		var ret string
		return ret
	}
	return *o.LastLogin.Get()
}

// GetLastLoginOk returns a tuple with the LastLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayersResponseProfile) GetLastLoginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLogin.Get(), o.LastLogin.IsSet()
}

// HasLastLogin returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasLastLogin() bool {
	if o != nil && o.LastLogin.IsSet() {
		return true
	}

	return false
}

// SetLastLogin gets a reference to the given NullableString and assigns it to the LastLogin field.
func (o *PlayersResponseProfile) SetLastLogin(v string) {
	o.LastLogin.Set(&v)
}
// SetLastLoginNil sets the value for LastLogin to be an explicit nil
func (o *PlayersResponseProfile) SetLastLoginNil() {
	o.LastLogin.Set(nil)
}

// UnsetLastLogin ensures that no value is present for LastLogin, not even an explicit nil
func (o *PlayersResponseProfile) UnsetLastLogin() {
	o.LastLogin.Unset()
}

// GetLoccountrycode returns the Loccountrycode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayersResponseProfile) GetLoccountrycode() string {
	if o == nil || IsNil(o.Loccountrycode.Get()) {
		var ret string
		return ret
	}
	return *o.Loccountrycode.Get()
}

// GetLoccountrycodeOk returns a tuple with the Loccountrycode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayersResponseProfile) GetLoccountrycodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Loccountrycode.Get(), o.Loccountrycode.IsSet()
}

// HasLoccountrycode returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasLoccountrycode() bool {
	if o != nil && o.Loccountrycode.IsSet() {
		return true
	}

	return false
}

// SetLoccountrycode gets a reference to the given NullableString and assigns it to the Loccountrycode field.
func (o *PlayersResponseProfile) SetLoccountrycode(v string) {
	o.Loccountrycode.Set(&v)
}
// SetLoccountrycodeNil sets the value for Loccountrycode to be an explicit nil
func (o *PlayersResponseProfile) SetLoccountrycodeNil() {
	o.Loccountrycode.Set(nil)
}

// UnsetLoccountrycode ensures that no value is present for Loccountrycode, not even an explicit nil
func (o *PlayersResponseProfile) UnsetLoccountrycode() {
	o.Loccountrycode.Unset()
}

// GetIsContributor returns the IsContributor field value if set, zero value otherwise.
func (o *PlayersResponseProfile) GetIsContributor() bool {
	if o == nil || IsNil(o.IsContributor) {
		var ret bool
		return ret
	}
	return *o.IsContributor
}

// GetIsContributorOk returns a tuple with the IsContributor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayersResponseProfile) GetIsContributorOk() (*bool, bool) {
	if o == nil || IsNil(o.IsContributor) {
		return nil, false
	}
	return o.IsContributor, true
}

// HasIsContributor returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasIsContributor() bool {
	if o != nil && !IsNil(o.IsContributor) {
		return true
	}

	return false
}

// SetIsContributor gets a reference to the given bool and assigns it to the IsContributor field.
func (o *PlayersResponseProfile) SetIsContributor(v bool) {
	o.IsContributor = &v
}

// GetIsSubscriber returns the IsSubscriber field value if set, zero value otherwise.
func (o *PlayersResponseProfile) GetIsSubscriber() bool {
	if o == nil || IsNil(o.IsSubscriber) {
		var ret bool
		return ret
	}
	return *o.IsSubscriber
}

// GetIsSubscriberOk returns a tuple with the IsSubscriber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayersResponseProfile) GetIsSubscriberOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSubscriber) {
		return nil, false
	}
	return o.IsSubscriber, true
}

// HasIsSubscriber returns a boolean if a field has been set.
func (o *PlayersResponseProfile) HasIsSubscriber() bool {
	if o != nil && !IsNil(o.IsSubscriber) {
		return true
	}

	return false
}

// SetIsSubscriber gets a reference to the given bool and assigns it to the IsSubscriber field.
func (o *PlayersResponseProfile) SetIsSubscriber(v bool) {
	o.IsSubscriber = &v
}

func (o PlayersResponseProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlayersResponseProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if o.Personaname.IsSet() {
		toSerialize["personaname"] = o.Personaname.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if !IsNil(o.Plus) {
		toSerialize["plus"] = o.Plus
	}
	if o.Cheese.IsSet() {
		toSerialize["cheese"] = o.Cheese.Get()
	}
	if o.Steamid.IsSet() {
		toSerialize["steamid"] = o.Steamid.Get()
	}
	if o.Avatar.IsSet() {
		toSerialize["avatar"] = o.Avatar.Get()
	}
	if o.Avatarmedium.IsSet() {
		toSerialize["avatarmedium"] = o.Avatarmedium.Get()
	}
	if o.Avatarfull.IsSet() {
		toSerialize["avatarfull"] = o.Avatarfull.Get()
	}
	if o.Profileurl.IsSet() {
		toSerialize["profileurl"] = o.Profileurl.Get()
	}
	if o.LastLogin.IsSet() {
		toSerialize["last_login"] = o.LastLogin.Get()
	}
	if o.Loccountrycode.IsSet() {
		toSerialize["loccountrycode"] = o.Loccountrycode.Get()
	}
	if !IsNil(o.IsContributor) {
		toSerialize["is_contributor"] = o.IsContributor
	}
	if !IsNil(o.IsSubscriber) {
		toSerialize["is_subscriber"] = o.IsSubscriber
	}
	return toSerialize, nil
}

type NullablePlayersResponseProfile struct {
	value *PlayersResponseProfile
	isSet bool
}

func (v NullablePlayersResponseProfile) Get() *PlayersResponseProfile {
	return v.value
}

func (v *NullablePlayersResponseProfile) Set(val *PlayersResponseProfile) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayersResponseProfile) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayersResponseProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayersResponseProfile(val *PlayersResponseProfile) *NullablePlayersResponseProfile {
	return &NullablePlayersResponseProfile{value: val, isSet: true}
}

func (v NullablePlayersResponseProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlayersResponseProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


