/*
OpenDota API

# Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     

API version: 25.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HeroItemPopularityResponseLateGameItems type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HeroItemPopularityResponseLateGameItems{}

// HeroItemPopularityResponseLateGameItems Items bought at least 25 min after game started, with cost at least 4000
type HeroItemPopularityResponseLateGameItems struct {
	// Number of item bought
	Item *int32 `json:"item,omitempty"`
}

// NewHeroItemPopularityResponseLateGameItems instantiates a new HeroItemPopularityResponseLateGameItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeroItemPopularityResponseLateGameItems() *HeroItemPopularityResponseLateGameItems {
	this := HeroItemPopularityResponseLateGameItems{}
	return &this
}

// NewHeroItemPopularityResponseLateGameItemsWithDefaults instantiates a new HeroItemPopularityResponseLateGameItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeroItemPopularityResponseLateGameItemsWithDefaults() *HeroItemPopularityResponseLateGameItems {
	this := HeroItemPopularityResponseLateGameItems{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *HeroItemPopularityResponseLateGameItems) GetItem() int32 {
	if o == nil || IsNil(o.Item) {
		var ret int32
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeroItemPopularityResponseLateGameItems) GetItemOk() (*int32, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *HeroItemPopularityResponseLateGameItems) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given int32 and assigns it to the Item field.
func (o *HeroItemPopularityResponseLateGameItems) SetItem(v int32) {
	o.Item = &v
}

func (o HeroItemPopularityResponseLateGameItems) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HeroItemPopularityResponseLateGameItems) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableHeroItemPopularityResponseLateGameItems struct {
	value *HeroItemPopularityResponseLateGameItems
	isSet bool
}

func (v NullableHeroItemPopularityResponseLateGameItems) Get() *HeroItemPopularityResponseLateGameItems {
	return v.value
}

func (v *NullableHeroItemPopularityResponseLateGameItems) Set(val *HeroItemPopularityResponseLateGameItems) {
	v.value = val
	v.isSet = true
}

func (v NullableHeroItemPopularityResponseLateGameItems) IsSet() bool {
	return v.isSet
}

func (v *NullableHeroItemPopularityResponseLateGameItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeroItemPopularityResponseLateGameItems(val *HeroItemPopularityResponseLateGameItems) *NullableHeroItemPopularityResponseLateGameItems {
	return &NullableHeroItemPopularityResponseLateGameItems{value: val, isSet: true}
}

func (v NullableHeroItemPopularityResponseLateGameItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeroItemPopularityResponseLateGameItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


