/*
OpenDota API

# Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     

API version: 25.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HeroItemPopularityResponseStartGameItems type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HeroItemPopularityResponseStartGameItems{}

// HeroItemPopularityResponseStartGameItems Items bought before game started
type HeroItemPopularityResponseStartGameItems struct {
	// Number of item bought
	Item *int32 `json:"item,omitempty"`
}

// NewHeroItemPopularityResponseStartGameItems instantiates a new HeroItemPopularityResponseStartGameItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeroItemPopularityResponseStartGameItems() *HeroItemPopularityResponseStartGameItems {
	this := HeroItemPopularityResponseStartGameItems{}
	return &this
}

// NewHeroItemPopularityResponseStartGameItemsWithDefaults instantiates a new HeroItemPopularityResponseStartGameItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeroItemPopularityResponseStartGameItemsWithDefaults() *HeroItemPopularityResponseStartGameItems {
	this := HeroItemPopularityResponseStartGameItems{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *HeroItemPopularityResponseStartGameItems) GetItem() int32 {
	if o == nil || IsNil(o.Item) {
		var ret int32
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeroItemPopularityResponseStartGameItems) GetItemOk() (*int32, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *HeroItemPopularityResponseStartGameItems) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given int32 and assigns it to the Item field.
func (o *HeroItemPopularityResponseStartGameItems) SetItem(v int32) {
	o.Item = &v
}

func (o HeroItemPopularityResponseStartGameItems) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HeroItemPopularityResponseStartGameItems) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableHeroItemPopularityResponseStartGameItems struct {
	value *HeroItemPopularityResponseStartGameItems
	isSet bool
}

func (v NullableHeroItemPopularityResponseStartGameItems) Get() *HeroItemPopularityResponseStartGameItems {
	return v.value
}

func (v *NullableHeroItemPopularityResponseStartGameItems) Set(val *HeroItemPopularityResponseStartGameItems) {
	v.value = val
	v.isSet = true
}

func (v NullableHeroItemPopularityResponseStartGameItems) IsSet() bool {
	return v.isSet
}

func (v *NullableHeroItemPopularityResponseStartGameItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeroItemPopularityResponseStartGameItems(val *HeroItemPopularityResponseStartGameItems) *NullableHeroItemPopularityResponseStartGameItems {
	return &NullableHeroItemPopularityResponseStartGameItems{value: val, isSet: true}
}

func (v NullableHeroItemPopularityResponseStartGameItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeroItemPopularityResponseStartGameItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


