/*
OpenDota API

# Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     

API version: 25.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DistributionsResponseRanksSum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributionsResponseRanksSum{}

// DistributionsResponseRanksSum sum
type DistributionsResponseRanksSum struct {
	// count
	Count *int32 `json:"count,omitempty"`
}

// NewDistributionsResponseRanksSum instantiates a new DistributionsResponseRanksSum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributionsResponseRanksSum() *DistributionsResponseRanksSum {
	this := DistributionsResponseRanksSum{}
	return &this
}

// NewDistributionsResponseRanksSumWithDefaults instantiates a new DistributionsResponseRanksSum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributionsResponseRanksSumWithDefaults() *DistributionsResponseRanksSum {
	this := DistributionsResponseRanksSum{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *DistributionsResponseRanksSum) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistributionsResponseRanksSum) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *DistributionsResponseRanksSum) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *DistributionsResponseRanksSum) SetCount(v int32) {
	o.Count = &v
}

func (o DistributionsResponseRanksSum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributionsResponseRanksSum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableDistributionsResponseRanksSum struct {
	value *DistributionsResponseRanksSum
	isSet bool
}

func (v NullableDistributionsResponseRanksSum) Get() *DistributionsResponseRanksSum {
	return v.value
}

func (v *NullableDistributionsResponseRanksSum) Set(val *DistributionsResponseRanksSum) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributionsResponseRanksSum) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributionsResponseRanksSum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributionsResponseRanksSum(val *DistributionsResponseRanksSum) *NullableDistributionsResponseRanksSum {
	return &NullableDistributionsResponseRanksSum{value: val, isSet: true}
}

func (v NullableDistributionsResponseRanksSum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributionsResponseRanksSum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


