/*
OpenDota API

# Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     

API version: 25.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PlayerMatchesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlayerMatchesResponse{}

// PlayerMatchesResponse Object containing information on the match
type PlayerMatchesResponse struct {
	// The ID number of the match assigned by Valve
	MatchId *int32 `json:"match_id,omitempty"`
	// Which slot the player is in. 0-127 are Radiant, 128-255 are Dire
	PlayerSlot NullableInt32 `json:"player_slot,omitempty"`
	// Boolean indicating whether Radiant won the match
	RadiantWin NullableBool `json:"radiant_win,omitempty"`
	// Duration of the game in seconds
	Duration *int32 `json:"duration,omitempty"`
	// Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json
	GameMode *int32 `json:"game_mode,omitempty"`
	// Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json
	LobbyType *int32 `json:"lobby_type,omitempty"`
	// The ID value of the hero played
	HeroId *int32 `json:"hero_id,omitempty"`
	// The Unix timestamp at which the game started
	StartTime *int32 `json:"start_time,omitempty"`
	// version
	Version NullableInt32 `json:"version,omitempty"`
	// Total kills the player had at the end of the game
	Kills *int32 `json:"kills,omitempty"`
	// Total deaths the player had at the end of the game
	Deaths *int32 `json:"deaths,omitempty"`
	// Total assists the player had at the end of the game
	Assists *int32 `json:"assists,omitempty"`
	// Skill bracket assigned by Valve (Normal, High, Very High)
	Skill NullableInt32 `json:"skill,omitempty"`
	// Average rank of players with public match data
	AverageRank NullableInt32 `json:"average_rank,omitempty"`
	// Integer describing whether or not the player left the game. 0: didn't leave. 1: left safely. 2+: Abandoned
	LeaverStatus *int32 `json:"leaver_status,omitempty"`
	// Size of the player's party
	PartySize NullableInt32 `json:"party_size,omitempty"`
}

// NewPlayerMatchesResponse instantiates a new PlayerMatchesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayerMatchesResponse() *PlayerMatchesResponse {
	this := PlayerMatchesResponse{}
	return &this
}

// NewPlayerMatchesResponseWithDefaults instantiates a new PlayerMatchesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayerMatchesResponseWithDefaults() *PlayerMatchesResponse {
	this := PlayerMatchesResponse{}
	return &this
}

// GetMatchId returns the MatchId field value if set, zero value otherwise.
func (o *PlayerMatchesResponse) GetMatchId() int32 {
	if o == nil || IsNil(o.MatchId) {
		var ret int32
		return ret
	}
	return *o.MatchId
}

// GetMatchIdOk returns a tuple with the MatchId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerMatchesResponse) GetMatchIdOk() (*int32, bool) {
	if o == nil || IsNil(o.MatchId) {
		return nil, false
	}
	return o.MatchId, true
}

// HasMatchId returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasMatchId() bool {
	if o != nil && !IsNil(o.MatchId) {
		return true
	}

	return false
}

// SetMatchId gets a reference to the given int32 and assigns it to the MatchId field.
func (o *PlayerMatchesResponse) SetMatchId(v int32) {
	o.MatchId = &v
}

// GetPlayerSlot returns the PlayerSlot field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerMatchesResponse) GetPlayerSlot() int32 {
	if o == nil || IsNil(o.PlayerSlot.Get()) {
		var ret int32
		return ret
	}
	return *o.PlayerSlot.Get()
}

// GetPlayerSlotOk returns a tuple with the PlayerSlot field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerMatchesResponse) GetPlayerSlotOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlayerSlot.Get(), o.PlayerSlot.IsSet()
}

// HasPlayerSlot returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasPlayerSlot() bool {
	if o != nil && o.PlayerSlot.IsSet() {
		return true
	}

	return false
}

// SetPlayerSlot gets a reference to the given NullableInt32 and assigns it to the PlayerSlot field.
func (o *PlayerMatchesResponse) SetPlayerSlot(v int32) {
	o.PlayerSlot.Set(&v)
}
// SetPlayerSlotNil sets the value for PlayerSlot to be an explicit nil
func (o *PlayerMatchesResponse) SetPlayerSlotNil() {
	o.PlayerSlot.Set(nil)
}

// UnsetPlayerSlot ensures that no value is present for PlayerSlot, not even an explicit nil
func (o *PlayerMatchesResponse) UnsetPlayerSlot() {
	o.PlayerSlot.Unset()
}

// GetRadiantWin returns the RadiantWin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerMatchesResponse) GetRadiantWin() bool {
	if o == nil || IsNil(o.RadiantWin.Get()) {
		var ret bool
		return ret
	}
	return *o.RadiantWin.Get()
}

// GetRadiantWinOk returns a tuple with the RadiantWin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerMatchesResponse) GetRadiantWinOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RadiantWin.Get(), o.RadiantWin.IsSet()
}

// HasRadiantWin returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasRadiantWin() bool {
	if o != nil && o.RadiantWin.IsSet() {
		return true
	}

	return false
}

// SetRadiantWin gets a reference to the given NullableBool and assigns it to the RadiantWin field.
func (o *PlayerMatchesResponse) SetRadiantWin(v bool) {
	o.RadiantWin.Set(&v)
}
// SetRadiantWinNil sets the value for RadiantWin to be an explicit nil
func (o *PlayerMatchesResponse) SetRadiantWinNil() {
	o.RadiantWin.Set(nil)
}

// UnsetRadiantWin ensures that no value is present for RadiantWin, not even an explicit nil
func (o *PlayerMatchesResponse) UnsetRadiantWin() {
	o.RadiantWin.Unset()
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *PlayerMatchesResponse) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerMatchesResponse) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *PlayerMatchesResponse) SetDuration(v int32) {
	o.Duration = &v
}

// GetGameMode returns the GameMode field value if set, zero value otherwise.
func (o *PlayerMatchesResponse) GetGameMode() int32 {
	if o == nil || IsNil(o.GameMode) {
		var ret int32
		return ret
	}
	return *o.GameMode
}

// GetGameModeOk returns a tuple with the GameMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerMatchesResponse) GetGameModeOk() (*int32, bool) {
	if o == nil || IsNil(o.GameMode) {
		return nil, false
	}
	return o.GameMode, true
}

// HasGameMode returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasGameMode() bool {
	if o != nil && !IsNil(o.GameMode) {
		return true
	}

	return false
}

// SetGameMode gets a reference to the given int32 and assigns it to the GameMode field.
func (o *PlayerMatchesResponse) SetGameMode(v int32) {
	o.GameMode = &v
}

// GetLobbyType returns the LobbyType field value if set, zero value otherwise.
func (o *PlayerMatchesResponse) GetLobbyType() int32 {
	if o == nil || IsNil(o.LobbyType) {
		var ret int32
		return ret
	}
	return *o.LobbyType
}

// GetLobbyTypeOk returns a tuple with the LobbyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerMatchesResponse) GetLobbyTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.LobbyType) {
		return nil, false
	}
	return o.LobbyType, true
}

// HasLobbyType returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasLobbyType() bool {
	if o != nil && !IsNil(o.LobbyType) {
		return true
	}

	return false
}

// SetLobbyType gets a reference to the given int32 and assigns it to the LobbyType field.
func (o *PlayerMatchesResponse) SetLobbyType(v int32) {
	o.LobbyType = &v
}

// GetHeroId returns the HeroId field value if set, zero value otherwise.
func (o *PlayerMatchesResponse) GetHeroId() int32 {
	if o == nil || IsNil(o.HeroId) {
		var ret int32
		return ret
	}
	return *o.HeroId
}

// GetHeroIdOk returns a tuple with the HeroId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerMatchesResponse) GetHeroIdOk() (*int32, bool) {
	if o == nil || IsNil(o.HeroId) {
		return nil, false
	}
	return o.HeroId, true
}

// HasHeroId returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasHeroId() bool {
	if o != nil && !IsNil(o.HeroId) {
		return true
	}

	return false
}

// SetHeroId gets a reference to the given int32 and assigns it to the HeroId field.
func (o *PlayerMatchesResponse) SetHeroId(v int32) {
	o.HeroId = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *PlayerMatchesResponse) GetStartTime() int32 {
	if o == nil || IsNil(o.StartTime) {
		var ret int32
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerMatchesResponse) GetStartTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given int32 and assigns it to the StartTime field.
func (o *PlayerMatchesResponse) SetStartTime(v int32) {
	o.StartTime = &v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerMatchesResponse) GetVersion() int32 {
	if o == nil || IsNil(o.Version.Get()) {
		var ret int32
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerMatchesResponse) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableInt32 and assigns it to the Version field.
func (o *PlayerMatchesResponse) SetVersion(v int32) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *PlayerMatchesResponse) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *PlayerMatchesResponse) UnsetVersion() {
	o.Version.Unset()
}

// GetKills returns the Kills field value if set, zero value otherwise.
func (o *PlayerMatchesResponse) GetKills() int32 {
	if o == nil || IsNil(o.Kills) {
		var ret int32
		return ret
	}
	return *o.Kills
}

// GetKillsOk returns a tuple with the Kills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerMatchesResponse) GetKillsOk() (*int32, bool) {
	if o == nil || IsNil(o.Kills) {
		return nil, false
	}
	return o.Kills, true
}

// HasKills returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasKills() bool {
	if o != nil && !IsNil(o.Kills) {
		return true
	}

	return false
}

// SetKills gets a reference to the given int32 and assigns it to the Kills field.
func (o *PlayerMatchesResponse) SetKills(v int32) {
	o.Kills = &v
}

// GetDeaths returns the Deaths field value if set, zero value otherwise.
func (o *PlayerMatchesResponse) GetDeaths() int32 {
	if o == nil || IsNil(o.Deaths) {
		var ret int32
		return ret
	}
	return *o.Deaths
}

// GetDeathsOk returns a tuple with the Deaths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerMatchesResponse) GetDeathsOk() (*int32, bool) {
	if o == nil || IsNil(o.Deaths) {
		return nil, false
	}
	return o.Deaths, true
}

// HasDeaths returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasDeaths() bool {
	if o != nil && !IsNil(o.Deaths) {
		return true
	}

	return false
}

// SetDeaths gets a reference to the given int32 and assigns it to the Deaths field.
func (o *PlayerMatchesResponse) SetDeaths(v int32) {
	o.Deaths = &v
}

// GetAssists returns the Assists field value if set, zero value otherwise.
func (o *PlayerMatchesResponse) GetAssists() int32 {
	if o == nil || IsNil(o.Assists) {
		var ret int32
		return ret
	}
	return *o.Assists
}

// GetAssistsOk returns a tuple with the Assists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerMatchesResponse) GetAssistsOk() (*int32, bool) {
	if o == nil || IsNil(o.Assists) {
		return nil, false
	}
	return o.Assists, true
}

// HasAssists returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasAssists() bool {
	if o != nil && !IsNil(o.Assists) {
		return true
	}

	return false
}

// SetAssists gets a reference to the given int32 and assigns it to the Assists field.
func (o *PlayerMatchesResponse) SetAssists(v int32) {
	o.Assists = &v
}

// GetSkill returns the Skill field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerMatchesResponse) GetSkill() int32 {
	if o == nil || IsNil(o.Skill.Get()) {
		var ret int32
		return ret
	}
	return *o.Skill.Get()
}

// GetSkillOk returns a tuple with the Skill field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerMatchesResponse) GetSkillOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Skill.Get(), o.Skill.IsSet()
}

// HasSkill returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasSkill() bool {
	if o != nil && o.Skill.IsSet() {
		return true
	}

	return false
}

// SetSkill gets a reference to the given NullableInt32 and assigns it to the Skill field.
func (o *PlayerMatchesResponse) SetSkill(v int32) {
	o.Skill.Set(&v)
}
// SetSkillNil sets the value for Skill to be an explicit nil
func (o *PlayerMatchesResponse) SetSkillNil() {
	o.Skill.Set(nil)
}

// UnsetSkill ensures that no value is present for Skill, not even an explicit nil
func (o *PlayerMatchesResponse) UnsetSkill() {
	o.Skill.Unset()
}

// GetAverageRank returns the AverageRank field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerMatchesResponse) GetAverageRank() int32 {
	if o == nil || IsNil(o.AverageRank.Get()) {
		var ret int32
		return ret
	}
	return *o.AverageRank.Get()
}

// GetAverageRankOk returns a tuple with the AverageRank field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerMatchesResponse) GetAverageRankOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AverageRank.Get(), o.AverageRank.IsSet()
}

// HasAverageRank returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasAverageRank() bool {
	if o != nil && o.AverageRank.IsSet() {
		return true
	}

	return false
}

// SetAverageRank gets a reference to the given NullableInt32 and assigns it to the AverageRank field.
func (o *PlayerMatchesResponse) SetAverageRank(v int32) {
	o.AverageRank.Set(&v)
}
// SetAverageRankNil sets the value for AverageRank to be an explicit nil
func (o *PlayerMatchesResponse) SetAverageRankNil() {
	o.AverageRank.Set(nil)
}

// UnsetAverageRank ensures that no value is present for AverageRank, not even an explicit nil
func (o *PlayerMatchesResponse) UnsetAverageRank() {
	o.AverageRank.Unset()
}

// GetLeaverStatus returns the LeaverStatus field value if set, zero value otherwise.
func (o *PlayerMatchesResponse) GetLeaverStatus() int32 {
	if o == nil || IsNil(o.LeaverStatus) {
		var ret int32
		return ret
	}
	return *o.LeaverStatus
}

// GetLeaverStatusOk returns a tuple with the LeaverStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerMatchesResponse) GetLeaverStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.LeaverStatus) {
		return nil, false
	}
	return o.LeaverStatus, true
}

// HasLeaverStatus returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasLeaverStatus() bool {
	if o != nil && !IsNil(o.LeaverStatus) {
		return true
	}

	return false
}

// SetLeaverStatus gets a reference to the given int32 and assigns it to the LeaverStatus field.
func (o *PlayerMatchesResponse) SetLeaverStatus(v int32) {
	o.LeaverStatus = &v
}

// GetPartySize returns the PartySize field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerMatchesResponse) GetPartySize() int32 {
	if o == nil || IsNil(o.PartySize.Get()) {
		var ret int32
		return ret
	}
	return *o.PartySize.Get()
}

// GetPartySizeOk returns a tuple with the PartySize field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerMatchesResponse) GetPartySizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PartySize.Get(), o.PartySize.IsSet()
}

// HasPartySize returns a boolean if a field has been set.
func (o *PlayerMatchesResponse) HasPartySize() bool {
	if o != nil && o.PartySize.IsSet() {
		return true
	}

	return false
}

// SetPartySize gets a reference to the given NullableInt32 and assigns it to the PartySize field.
func (o *PlayerMatchesResponse) SetPartySize(v int32) {
	o.PartySize.Set(&v)
}
// SetPartySizeNil sets the value for PartySize to be an explicit nil
func (o *PlayerMatchesResponse) SetPartySizeNil() {
	o.PartySize.Set(nil)
}

// UnsetPartySize ensures that no value is present for PartySize, not even an explicit nil
func (o *PlayerMatchesResponse) UnsetPartySize() {
	o.PartySize.Unset()
}

func (o PlayerMatchesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlayerMatchesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MatchId) {
		toSerialize["match_id"] = o.MatchId
	}
	if o.PlayerSlot.IsSet() {
		toSerialize["player_slot"] = o.PlayerSlot.Get()
	}
	if o.RadiantWin.IsSet() {
		toSerialize["radiant_win"] = o.RadiantWin.Get()
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.GameMode) {
		toSerialize["game_mode"] = o.GameMode
	}
	if !IsNil(o.LobbyType) {
		toSerialize["lobby_type"] = o.LobbyType
	}
	if !IsNil(o.HeroId) {
		toSerialize["hero_id"] = o.HeroId
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	if !IsNil(o.Kills) {
		toSerialize["kills"] = o.Kills
	}
	if !IsNil(o.Deaths) {
		toSerialize["deaths"] = o.Deaths
	}
	if !IsNil(o.Assists) {
		toSerialize["assists"] = o.Assists
	}
	if o.Skill.IsSet() {
		toSerialize["skill"] = o.Skill.Get()
	}
	if o.AverageRank.IsSet() {
		toSerialize["average_rank"] = o.AverageRank.Get()
	}
	if !IsNil(o.LeaverStatus) {
		toSerialize["leaver_status"] = o.LeaverStatus
	}
	if o.PartySize.IsSet() {
		toSerialize["party_size"] = o.PartySize.Get()
	}
	return toSerialize, nil
}

type NullablePlayerMatchesResponse struct {
	value *PlayerMatchesResponse
	isSet bool
}

func (v NullablePlayerMatchesResponse) Get() *PlayerMatchesResponse {
	return v.value
}

func (v *NullablePlayerMatchesResponse) Set(val *PlayerMatchesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayerMatchesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayerMatchesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayerMatchesResponse(val *PlayerMatchesResponse) *NullablePlayerMatchesResponse {
	return &NullablePlayerMatchesResponse{value: val, isSet: true}
}

func (v NullablePlayerMatchesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlayerMatchesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


